#! /usr/bin/env python

import os, sys, pprint
sys.path.insert(0, '..')

from bacula_tools import parser
retval= parser(open('/usr/local/etc/bacula-dir.conf').read())
print len(retval)
pprint.pprint(retval)
