#! /usr/bin/env python

import os
import sys
import pprint
import logging
# logging.basicConfig(level=logging.DEBUG)
sys.path.insert(0, '..')
sys.path.insert(0, '.')
import bacula_tools
import bacula_tools.parser_support

test_cases = ['''    Name = File
  Address = 127.0.0.1                
  SDPort = 9103
  Password = "lLpGzQjpOwCGtUKkSwFWuLNAFsi7Bmpq1bHGtsf/213T"
  Device = FileStorage
  Media Type = File
''',
              '''  Name = DDS-4
  Address = outbidoverdrive
  SDPort = 9103
  Password = "lLpGzQjpOwCGtUKkSwFWuLNAFsi7Bmpq1bHGtsf/213T"
  Device = DDS-4
  Media Type = DDS-4
  Autochanger = yes
''',
              '''  Name = "8mmDrive"
  Address = outbidoverdrive
  SDPort = 9103
  Password = "lLpGzQjpOwCGtUKkSwFWuLNAFsi7Bmpq1bHGtsf/213T"
  Device = "Exabyte 8mm"
  MediaType = "8mm"
''',
              '''  Name = "DVD"
  Address = outbidoverdrive
  SDPort = 9103
  Password = "lLpGzQjpOwCGtUKkSwFWuLNAFsi7Bmpq1bHGtsf/213T"
  Device = "DVD Writer"
  MediaType = "DVD"
''',
              '''  Name = outbidoverdrive.gallew.org-sd
  SDPort = 9103
  WorkingDirectory = "/usr/local/Cellar/bacula/5.2.13/opt/bacula/working"
  Pid Directory = "/var/run"
  Maximum Concurrent Jobs = 20''',

              ]

# let's hope there's a director
for string in test_cases:
    bacula_tools.parser_support.setup_for_parsing()
    c = bacula_tools.Storage()
    c.parse_string(string)
    # print c
    print c.fd()
    print c.sd()
