#! /usr/bin/env python

import os, sys, pprint
sys.path.insert(0, '..')
sys.path.insert(0, '.')
import bacula_tools

string='''  Name = bs-sd001
  Pool Type = Backup
  Recycle = yes
  AutoPrune = yes
  Volume Retention = 60 days
  Maximum Volume Jobs = 1
  Label Format = bs-sd001-
  Action On Purge = Truncate
'''
c = bacula_tools.Pool()
c.parse_string(string)

print c
print c.fd()
